# Specify xenial linux distribution and minimal language support
sudo: required
language: generic
dist: xenial

# Setup build cache
cache:
  apt: true
  ccache: true
  directories:
    - $HOME/.ccache
    - /tmp/beam_dependencies

# Set global variables
env:
  global:
    - CI_SOURCE_PATH=$(pwd)
    - CONTINUOUS_INTEGRATION='True'

# Check installation script
install:
  - cd $CI_SOURCE_PATH
  - travis_wait 120 bash ./scripts/install.bash

# Run unit test scripts
